import { mkdirSync } from 'node:fs';
import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createClient } from '@libsql/client';
import { drizzle, type LibSQLDatabase } from 'drizzle-orm/libsql';
import { migrate } from 'drizzle-orm/libsql/migrator';
import * as schema from './schema.js';

export type Db = LibSQLDatabase<typeof schema>;

/** The SQL migrations generated by drizzle-kit (`pnpm db:generate`). */
export const MIGRATIONS = fileURLToPath(new URL('../../drizzle', import.meta.url));

const isFile = (url: string): boolean => url.startsWith('file:') && url !== 'file::memory:';

/**
 * Opens the database with foreign keys enforced. libsql already enables them by default
 * (plain SQLite does not); the explicit pragma keeps that guarantee if the driver changes.
 *
 * File databases use WAL with synchronous=NORMAL (ADR 0001 addendum): readers never block on,
 * or fail with SQLITE_BUSY because of, a writer, so only writes need the lock in ./tx.ts. No
 * busy_timeout: libsql's driver is synchronous, so waiting would block the event loop an open
 * transaction needs; ./tx.ts retries busy writes asynchronously instead.
 * File URLs get their directory created.
 */
export async function openDb(url: string): Promise<Db> {
  if (isFile(url)) mkdirSync(dirname(url.slice('file:'.length)), { recursive: true });
  const client = createClient({ url });
  await client.execute('PRAGMA foreign_keys = ON');
  if (isFile(url)) {
    await client.execute('PRAGMA journal_mode = WAL');
    await client.execute('PRAGMA synchronous = NORMAL');
  }
  return drizzle(client, { schema });
}

export async function migrateDb(db: Db): Promise<void> {
  await migrate(db, { migrationsFolder: MIGRATIONS });
}

/** A fresh, migrated in-memory database for tests. */
export async function createTestDb(): Promise<Db> {
  const db = await openDb(':memory:');
  await migrateDb(db);
  return db;
}
