import { mkdirSync } from 'node:fs';
import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createClient } from '@libsql/client';
import { drizzle, type LibSQLDatabase } from 'drizzle-orm/libsql';
import { migrate } from 'drizzle-orm/libsql/migrator';
import * as schema from './schema.js';

export type Db = LibSQLDatabase<typeof schema>;

/** The SQL migrations generated by drizzle-kit (`pnpm db:generate`). */
export const MIGRATIONS = fileURLToPath(new URL('../../drizzle', import.meta.url));

/** Opens the database. File URLs get their directory created. */
export function openDb(url: string): Db {
  if (url.startsWith('file:') && url !== 'file::memory:') {
    mkdirSync(dirname(url.slice('file:'.length)), { recursive: true });
  }
  const client = createClient({ url });
  return drizzle(client, { schema });
}

export async function migrateDb(db: Db): Promise<void> {
  await db.run('PRAGMA foreign_keys = ON');
  await migrate(db, { migrationsFolder: MIGRATIONS });
}

/** A fresh, migrated in-memory database for tests. */
export async function createTestDb(): Promise<Db> {
  const db = openDb(':memory:');
  await migrateDb(db);
  return db;
}
